version: "3.9"

services:
  gateway:
    image: vineeshw1994/swarm-blog-gateway:latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: always
      update_config:
        parallelism: 1
        delay: 10s
